version: '3.8'

services:
  api-rest:
    container_name: api_rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    volumes:
      - .:/app
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    name: insured_ql_mynetwork
