default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] || 'your_app_development' %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] || 'your_app_test' %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] || 'your_app_production' %>
